CREATE TABLE `user` (
  `id` INTEGER AUTO_INCREMENT,
  `name` VARCHAR (15) NOT NULL ,
  `email` VARCHAR(50) NOT NULL ,
  `status` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `category` (
  `id` INTEGER AUTO_INCREMENT ,
  `name` VARCHAR (50) NOT NULL ,
  `status` INTEGER NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `post` (
  `id` INTEGER AUTO_INCREMENT,
  `user_id` INTEGER NOT NULL ,
  `content` VARCHAR(255) NOT NULL ,
  `status` INTEGER NOT NULL,
  `created_at` TIMESTAMP NOT NULL ,
  `updated_at` DATETIME  ,
  `category_id` INTEGER NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=MyISAM DEFAULT CHARSET=utf8;